name: CI Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/code_check.yaml
    secrets: inherit
    with:
      publish_performance: true
      store_benchmark: true
