name: CI Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited, closed ]

jobs:
  ci:
    uses: ./.github/workflows/code_check.yaml
    secrets:
      benchmark_token: ${{ secrets.BENCHMARK_TOKEN }}
    with:
      publish_performance: false
      store_benchmark: false
