name: CI Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/code_check.yaml
    secrets: inherit
    with:
      publish_performance: false
      store_benchmark: false
